PHEE-366 Updated region and parameterized
openMF/ph-ee-env-labs pull request #147
Opened 2023-07-24 06:51 UTC by dhruvsonagara

## Description

- [PHEE-366 Update region and parameterize in contexts](https://fynarfin.atlassian.net/browse/PHEE-366?atlOrigin=eyJpIjoiMDNkN2ViOWJmNzFhNDlhZjg1NjE1ZmVmODU3ZTY0MmUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design-related bullet points or design document links related to this PR are added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-07-25 12:38 UTC, truthfool commented
Related Jira Ticket : https://fynarfin.atlassian.net/browse/PHEE-346?atlOrigin=eyJpIjoiY2RhMGRiNzRiYmZhNDcwY2IxMDNmMzhlZWQwYjQ2MjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ

2023-07-26 08:36 UTC, fynmanoj requested changes

2023-07-26 08:36 UTC, fynmanoj commented on .circleci/config.yml
> +          kubectl config use-context arn:aws:eks:ap-south-1:419830066942:cluster/sit
why parameterized place holder is not used here?

2023-07-26 08:36 UTC, fynmanoj commented on helm/g2p-sandbox-fynarfin-SIT/values.yaml
> +        region: "ap-south-1"
This change cannot be applied as the S3 bucker is not created yet. please verify

2023-07-28 06:30 UTC, fynmanoj approved these changes

2023-07-28 06:31 UTC, merged