[GOV-83] P2G NonRTP TCs
openMF/ph-ee-env-labs pull request #227
Opened 2024-01-25 12:52 UTC by ankita10r

## Description

* PR title should have jira ticket enclosed in `[]`.<br>
  Format: ``` [jira_ticket] description```<br>
  ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!
- [ ] Followed the PR title naming convention mentioned above.

- [ ] Design-related bullet points or design document links related to this PR are added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2024-01-29 07:20 UTC, fynmanoj requested changes
Clarification requested

2024-01-29 07:20 UTC, fynmanoj commented on orchestration/bpmn/bill-inquiry-DFSPID.png
Why "not found" not end up in Failure?

2024-01-31 05:48 UTC, ankita10r commented on orchestration/bpmn/bill-inquiry-DFSPID.png
because even if the biller is not found the initiator (payer fsp) should get a callback stating why the txn failed

2024-02-02 09:31 UTC, fynmanoj approved these changes

2024-02-02 09:31 UTC, fynmanoj commented on orchestration/bpmn/bill-inquiry-DFSPID.png
Ideally this should be handled in the BPMN itself. BPMN should be able to depict the flow

2024-02-04 06:53 UTC, fynmanoj approved these changes

2024-02-04 06:54 UTC, merged