[PHEE-585] Fixed retry logic in bulk_processor_account_lookup BPMN
openMF/ph-ee-env-labs pull request #242
Opened 2024-02-15 13:47 UTC by shkr7

[PHEE-585 Fix Retry logic in bulk_processor_account_lookup-DFSPID.bpmn](https://fynarfin.atlassian.net/browse/PHEE-585?atlOrigin=eyJpIjoiMTc1Y2ZkNDQ4NmE5NGEzZGFmMjMwZjlhYWExNjdjZWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!
- [x] Followed the PR title naming convention mentioned above.

- [x] Design-related bullet points or design document links related to this PR are added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2024-02-15 15:08 UTC, fynmanoj requested changes
Check the image size

2024-02-15 15:08 UTC, fynmanoj commented on orchestration/bpmn/bulk_processor_account_lookup-DFSPID.png
The image is too small to view.

2024-02-16 11:07 UTC, shkr7 commented on orchestration/bpmn/bulk_processor_account_lookup-DFSPID.png
Okay, will fix it in the next revision.

2024-02-16 12:25 UTC, fynmanoj approved these changes

2024-02-16 12:25 UTC, merged