k6-operator added for load testing
openMF/ph-ee-env-labs pull request #49
Opened 2023-02-22 11:54 UTC by logoutdhaval

## Description

* Describe the changes made and why they were made.
* Add a link to teh design document or include the design bullet points related to this PR here.

 _(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above. 

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-02-23 14:33 UTC, somanath21 requested changes
97% of the code looks unnecessarily duplicated code.  Use this helm chart as a dependency and only override fields you require in values.yaml.

2023-02-23 14:33 UTC, somanath21 commented on helm/k6-operator/templates/prometheus/serviceMonitor.yaml
> +kind: ServiceMonitor
Prometheus has well known helm charts. Adding K8s manifests for these are not maintainable (unnecessary technical debt). Please replace with helm chart overriding of values.yaml if required.

2023-02-23 14:33 UTC, somanath21 commented on helm/k6-operator/e2e/test.js
> +//    address: "https://messagegateway.sandbox.fynarfin.io/sms",
Do you need this dead code?

2023-02-23 14:33 UTC, somanath21 commented on helm/k6-operator/Chart.yaml
> +appVersion: "0.0.6"
Don't duplicate code unnecessarily. Use this helm chart as a dependency and only override fields you require in values.yaml.

2023-02-23 14:33 UTC, somanath21 commented on helm/k6-operator/e2e/test.js
> +  const payload = JSON.stringify([{
This part looks like the only code other than values / Chart.yaml that might be required for this PR.

2023-02-23 14:33 UTC, somanath21 commented on helm/k6-operator/e2e/test.yaml
> +spec:
You can let this remain in the PR.

2023-05-24 15:14 UTC, fynmanoj commented
@logoutdhaval please address comments and get this PR merged

2023-05-25 05:23 UTC, closed without merging